name: "Build And Test Action"
description: "Builds and Tests bindle-dotnet"
inputs:
  configuration: 
    description: 'The Configration to build and test'
    required: true
    default: 'release'
runs:
  using: "composite"
  steps: 
    - name: Restore dependencies
      run: dotnet restore
      shell: bash
    - name: Set MINVERBUILDMETADATA
      run: echo MINVERBUILDMETADATA=$(git rev-parse --short ${GITHUB_SHA})  >> $GITHUB_ENV
      shell: bash
    - name: Build
      run: dotnet build -c ${{ inputs.configuration }}
      shell: bash
    - name: Build Bindle
      run: make build
      working-directory: bindleserver
      shell: bash
    - name: Test
      env:  
        BINDLE_SERVER_PATH: ../../../../bindleserver/target/debug
      run: dotnet test 
      shell: bash